### ISSUE TITLE
Make This Font a Variable Font

### ISSUE THREAD

**Issue by Bronnel721** [jasmurdo/Trocchi#34]
This font is great but it would be even better if it had more styles.
I want this font to have a variable font. And is that variable font I want to have three axis in it. Witch is the weight axis, (thin - black) the width axis, (ultra compressed - ultra wide) & the optical size axis. (4px - 144px)

**Comment by davelab6** [comment]
@MarcoMahone I too would like that. But who will pay for someone to do it? Let me know if you have an answer, otherwise, there's little point in asking for it. It's like asking for a new car. I too would like a new car.

**Comment by Bronnel721** [comment]
IDK. Also I do have a answer.

**Comment by davelab6** [comment]
Then I suggest to close the issue :)

**Comment by Bronnel721** [comment]
Why? 🤔

**Comment by davelab6** [comment]
It is extremely unlikely that any action will occur based on it.

**Comment by Bronnel721** [comment]
How come?
